### ISSUE TITLE
Auth Service

### ISSUE THREAD

**Issue by Ratstail91** [benawad/how-to-roll-your-own-auth#1]
hi there!

I just noticed you created this repo, and I wanted to throw this out there - https://github.com/krgamestudios/auth-server

I'm not looking to show off, I just wanted to offer my own auth service to start a discussion. And to show off.

It's generally recommended not to roll your own auth, but it's fine if you're willing to put in the leg work to get everything just right - that includes doing a heck of a lot of research.

Looking forward to the video on this!

(P.S. you might wanna convert this issue into a discussion.)

**Comment by wschaf** [comment]
![image](https://github.com/user-attachments/assets/ab37082f-3f6c-4ad5-b6eb-d9f44999cc03)

**Comment by Ratstail91** [comment]
> ![image](https://private-user-images.githubusercontent.com/8428074/350282956-ab37082f-3f6c-4ad5-b6eb-d9f44999cc03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MzgzNjksIm5iZiI6MTcyMTQzODA2OSwicGF0aCI6Ii84NDI4MDc0LzM1MDI4Mjk1Ni1hYjM3MDgyZi0zZjZjLTRhZDUtYjZlYi1kOWY0NDk5OWNjMDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjBUMDExNDI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzkxNTg2ZDJhZTNhNzc0OGEwYzA3ZWYwOWViZDJmNzE3ZTNmOTM5ZTc1NTkzZmIwYzQxMmFhZmUxZjUyMDZhYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ip2Pto8yewFvRS_xxlSczMDdclXWeWbAJcs9qsk5Gms)

I... IDGI?
