### ISSUE TITLE
The point of having two tokens if you auto refresh them?

### ISSUE THREAD

**Issue by BaptisteMartinet** [benawad/how-to-roll-your-own-auth#3]
Hey!
Auth newbie here, I would like to know what's the point of auto-refreshing the access token with the refresh one?
I feel like a single token would get you the same result.

**Comment by benawad** [comment]
1. If you have one token and you do a database request each time to check it then you basically just implemented sessions

2. If you have one token and it only lasts five minutes, then the user would have to constantly login

3. If you have one token and it lasts for a long time and you’re not doing database requests, then there’s no way to revoke the token early (you could do this if think you never need to revoke a token early)

**Comment by BaptisteMartinet** [comment]
I get it. It's all about revoking the refresh token.
Thanks for your answer.
