### ISSUE TITLE
Incrementing token version on each refresh?

### ISSUE THREAD

**Issue by ElorNorthwind** [benawad/how-to-roll-your-own-auth#5]
I apologize for a stupid question.
I absolutely adore the elegance of token version idea, but I just can't wrap my head around one thing:

In `api/src/createAuthTokens.ts` there seem to be a line of code that increments refresh token version each time that token is used.

It sounds like a good security measure that ensures the refresh token can effectively be only used once (something that is usually achieved by keeping a whitelist or a blacklist of tokens). 
But wouldn't it also log the user out of all other devices every 15 minutes (or whatever else the lifespan of access token would be), thus making this implementation impractical in any scenario that involves more than one device per user?

In the video guide (if I recall correctly) it was mentioned that incrementing the token version is only needed to emulate the "log out of all devices" functionality (or in case we need to log that user out for security reasons).

I am really confused as to which approach is intended. Maybe I actually missed the entire point completely...

**Comment by benawad** [comment]
That's a good catch. I think I had that in there for taking a screenshot, but you are right it shouldn't be there. I just removed it now

**Comment by ElorNorthwind** [comment]
Thanks for the quick answer!
I was worried I missed something vital in the authorization flow…
